version: '3'

services:

  postgres:
    container_name:  postgres
    image:           postgres:9.6
    restart: "on-failure"
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ../postgredb:/var/lib/postgresql/data
    env_file: ../.env
    environment:
      - LC_ALL=C.UTF-8

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  redis:
    image: redis:4.0.11
    restart: "on-failure"
    container_name: redis
    command: redis-server --requirepass dKqs72RhtaPPYyfN
    env_file: ../.env
    ports:
      - 6379:6379
    volumes:
      - ../redisdb:/var/lib/redis
