# Generated by Django 3.1.3 on 2020-12-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201208_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='post/covers', verbose_name='Cover image'),
        ),
    ]
