# Generated by Django 3.1.3 on 2020-12-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201208_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(null=True, verbose_name='Bio'),
        ),
    ]
