# Generated by Django 3.1.3 on 2020-12-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_author_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment message')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('commenter', models.CharField(max_length=150, verbose_name='Name')),
                ('website', models.CharField(max_length=200, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='core.Comment'),
        ),
    ]
