# Generated by Django 3.1.3 on 2020-12-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='core.Comment'),
        ),
    ]
