# Generated by Django 3.1.3 on 2020-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201209_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='core.Comment'),
        ),
    ]
