# Generated by Django 3.1.3 on 2020-12-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201210_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='View count'),
        ),
    ]
