# Generated by Django 3.1.3 on 2020-12-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201210_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_added',
            new_name='comment_added_at',
        ),
        migrations.AddField(
            model_name='category',
            name='featured_img',
            field=models.ImageField(null=True, upload_to='category/', verbose_name='Featured image'),
        ),
    ]
